apiVersion: apps/v1
kind: Deployment
metadata:
  name: bkhy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bkhy
  template:
    metadata:
      labels:
        app: bkhy
    spec:
      containers:
      - image: okteto.dev/bkhy:latest
        name: bkhy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a8edf705-8b80-467c-aa27-cb3da47597e6"
        - name: Vless_Path
          value: "/gdxcse3ew2q"
        - name: Vmess_UUID
          value: "a8edf705-8b80-467c-aa27-cb3da47597e6"
        - name: Vmess_Path
          value: "/gdb65erfd8iu"
        - name: Share_Path
          value: "/v2link"
