apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdxw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdxw
  template:
    metadata:
      labels:
        app: fdxw
    spec:
      containers:
      - image: okteto.dev/fdxw:latest
        name: fdxw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "799f3b4b-41a7-4900-8528-68b4c47d4034"
        - name: Vless_Path
          value: "/qaxs3de6gt"
        - name: Vmess_UUID
          value: "799f3b4b-41a7-4900-8528-68b4c47d4034"
        - name: Vmess_Path
          value: "/bvxc5de3ws"
        - name: Share_Path
          value: "/v2link"
